services:
  - type: web
    name: webluxe-fastapi
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
